name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
    validations:
      required: true
