package core

import (
	"fmt"
	"strings"

	"github.com/daybeam/vortex/config"
	"github.com/daybeam/vortex/schemas"
)

// WatchdogAlert represents a warning generated by the gateway watchdog.
type WatchdogAlert struct {
	Type    string
	Message string
}

// GatewayWatchdog sniffs for potential data conflicts in tool usage.
type GatewayWatchdog struct {
	registry *config.Registry
}

func NewGatewayWatchdog(reg *config.Registry) *GatewayWatchdog {
	return &GatewayWatchdog{registry: reg}
}

// Sniff analyzes a batch of tool calls for potential conflicts.
// It specifically looks for multiple external dynamic sources (e.g. search engines)
// being queried in the same turn for overlapping intents.
func (w *GatewayWatchdog) Sniff(calls []schemas.ToolCall, hub *ContextHub) *WatchdogAlert {
	if len(calls) < 2 {
		return nil
	}

	externalTools := make([]string, 0)
	toolCapabilities := make(map[string][]string)

	hub.Registry.Mu.RLock()
	defer hub.Registry.Mu.RUnlock()

	for _, call := range calls {
		// 1. Resolve source from Registry Skills
		if skill, ok := hub.Registry.Skills[call.Name]; ok {
			if skill.Source == config.SourceExternalDynamic {
				externalTools = append(externalTools, call.Name)
				toolCapabilities[call.Name] = []string{skill.Capability}
			}
			continue
		}

		// 2. Resolve source from Registry MCPs
		mcpFound := false
		for _, mcp := range hub.Registry.MCPs {
			for _, tool := range mcp.AvailableTools {
				if tool == call.Name {
					if mcp.Source == config.SourceExternalDynamic {
						externalTools = append(externalTools, call.Name)
						toolCapabilities[call.Name] = mcp.Provides
					}
					mcpFound = true
					break
				}
			}
			if mcpFound {
				break
			}
		}
		if mcpFound {
			continue
		}

		// 3. Check dynamic MCPs
		for _, mcp := range hub.Registry.DynamicMCPs {
			for _, tool := range mcp.AvailableTools {
				if tool == call.Name {
					if mcp.Source == config.SourceExternalDynamic {
						externalTools = append(externalTools, call.Name)
						toolCapabilities[call.Name] = mcp.Provides
					}
					break
				}
			}
		}
	}

	if len(externalTools) >= 2 {
		// Check for overlapping capabilities
		overlaps := make(map[string]bool)
		for i := 0; i < len(externalTools); i++ {
			for j := i + 1; j < len(externalTools); j++ {
				t1 := externalTools[i]
				t2 := externalTools[j]
				caps1 := toolCapabilities[t1]
				caps2 := toolCapabilities[t2]

				for _, c1 := range caps1 {
					for _, c2 := range caps2 {
						if c1 == c2 {
							overlaps[c1] = true
						}
					}
				}
			}
		}

		if len(overlaps) > 0 {
			overlapList := make([]string, 0, len(overlaps))
			for o := range overlaps {
				overlapList = append(overlapList, o)
			}

			return &WatchdogAlert{
				Type: "multi_source_conflict_probing",
				Message: fmt.Sprintf(
					"[WATCHDOG ALERT]: Multi-source conflict probing triggered. You are querying multiple external sources (%s) for overlapping capabilities [%s]. Please carefully cross-verify results for any discrepancies or conflicting data points before finalizing your answer.",
					strings.Join(externalTools, ", "),
					strings.Join(overlapList, ", "),
				),
			}
		}
	}

	return nil
}
